{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "modamoda.fullname" . }}-np
  labels:
    {{- include "modamoda.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "modamoda.selectorLabels" . | nindent 6 }}
  policyTypes: ["Ingress","Egress"]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.networkPolicy.ingressNamespace | default "ingress-nginx" }}
      ports:
        - port: http
          protocol: TCP
        - port: https
          protocol: TCP
  egress:
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.egressCIDR | default "0.0.0.0/0" }}
      ports:
        - port: 443
          protocol: TCP
{{- end }}
