{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "modamoda.fullname" . }}
  labels:
    {{- include "modamoda.labels" . | nindent 4 }}
    release: {{ .Values.monitoring.serviceMonitor.release | default "prom" }}
spec:
  selector:
    matchLabels:
      {{- include "modamoda.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval | default "30s" }}
{{- end }}
